backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "visuals"
    label: "Visuals"
    folder: "content"
    create: true
    delete: false
    slug: "visuals"
    fields:
      - { name: "realm", default: "visuals", widget: "hidden" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "file", label: "Yandex Link", widget: "string" }
      - { name: "thumbnail", label: "Thumbnail URL", widget: "string" }

  - name: "games"
    label: "Games"
    folder: "content"
    create: true
    delete: false
    slug: "games"
    fields:
      - { name: "realm", default: "games", widget: "hidden" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "file", label: "Yandex Link", widget: "string" }
      - { name: "thumbnail", label: "Thumbnail URL", widget: "string" }

  - name: "movies"
    label: "Movies"
    folder: "content"
    create: true
    delete: false
    slug: "movies"
    fields:
      - { name: "realm", default: "movies", widget: "hidden" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "file", label: "Yandex Link", widget: "string" }
      - { name: "thumbnail", label: "Thumbnail URL", widget: "string" }

  - name: "music"
    label: "Music"
    folder: "content"
    create: true
    delete: false
    slug: "music"
    fields:
      - { name: "realm", default: "music", widget: "hidden" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "file", label: "Yandex Link", widget: "string" }
      - { name: "thumbnail", label: "Thumbnail URL", widget: "string" }

  - name: "memes"
    label: "Memes"
    folder: "content"
    create: true
    delete: false
    slug: "memes"
    fields:
      - { name: "realm", default: "memes", widget: "hidden" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "file", label: "Yandex Link", widget: "string" }
      - { name: "thumbnail", label: "Thumbnail URL", widget: "string" }

  - name: "secrets"
    label: "Secrets"
    folder: "content"
    create: true
    delete: false
    slug: "secrets"
    fields:
      - { name: "realm", default: "secrets", widget: "hidden" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "file", label: "Yandex Link", widget: "string" }
      - { name: "thumbnail", label: "Thumbnail URL", widget: "string" }
